name: Deploy to ult-co.public

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Remove Old ult-co.public Folder Contents
      run: |
        rm -rf ult-co.public/*

    - name: Copy Content Folder to ult-co.public Folder
      run: |
        mkdir -p ult-co.public/content
        cp -r content/* ult-co.public/content/

    - name: Copy Index.html to ult-co.public Folder
      run: |
        cp index.html ult-co.public/

    - name: Commit Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ult-co.public/
        git commit -m "Deploy content to ult-co.public folder"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
