name: Deploy to Neocities

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: 🔍 Debug Secret Availability
      run: |
        echo "Checking NEOCITIES_API_TOKEN environment variable..."
        if [ -z "$NEOCITIES_API_TOKEN" ]; then
          echo "❌ NEOCITIES_API_TOKEN is missing!"
          exit 1
        else
          echo "✅ NEOCITIES_API_TOKEN is available (masked length: ${#NEOCITIES_API_TOKEN})"
        fi
      env:
        NEOCITIES_API_TOKEN: ${{ secrets.NEOCITIES_API_TOKEN }}

    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        neocities_supporter: true
        preview_before_deploy: true
        dist_dir: ult-co.public
